MVVM
KornilovMikhail/MVVMAndroidProject pull request #1
Opened 2019-03-25 19:31 UTC by KornilovMikhail

![image](https://user-images.githubusercontent.com/31703085/54948401-9c9b2480-4f4d-11e9-861d-bcf7bb1f7510.png)
![image](https://user-images.githubusercontent.com/31703085/54948420-a6248c80-4f4d-11e9-8533-5894c5ff70fa.png)

2019-03-27 23:29 UTC, NailShaykhrazievItis requested changes

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/data/mapper/NewsMappers.kt
> +
extra line

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/data/mapper/NewsMappers.kt
> +
extra line

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/data/repository/NewsLocalRepository.kt
> +        .map { it.map { mapNewsDBToNews(it) } }
на этом уровне было б не плохо еще задать поток для выполнения

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/data/repository/NewsNetworkRepository.kt
> +    fun getTopNews(): Single<List<News>> {
=

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/data/repository/NewsRepository.kt
> +    fun getTopNews(): Single<List<News>> {
=

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/data/repository/NewsRepository.kt
> +    private var isFirst = true
add single line after class beginning

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/data/repository/NewsRepository.kt
> +    fun cacheTopNews(newsList: List<News>) {
=

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/interactor/TopNewsInteractor.kt
> +    fun getTopNews(): Single<List<News>> = newsRepository.getTopNews()
add single line

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/interactor/TopNewsInteractor.kt
> +        }.subscribeOn(Schedulers.io())
тут конечно спорный момент, но дао всегда будет в ио, поэтому не вижу смысла управлять этим в интеракторе. Если б были кейса когда там было что т по разному, то да. А так бизнес логика на этом никак не строится и можно в репу закинуть

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newsdetail/NewsDetailFragment.kt
> +                makeToast(getString(R.string.server_load_success))
makeToast можно вынести за иф: 
makeToast( if (it) {})

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newsdetail/NewsDetailFragment.kt
> +            Observer { it?.let { details_progressBar.visibility = it } })
имхо данный способ написания кода не обеспечивает его читабельность. В фокусе this и Observer, которые тут совсем не важны. Метод ниже написан лучше

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newsdetail/NewsDetailFragment.kt
> +    private fun makeToast(text: String) {
=

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newsdetail/NewsDetailViewModel.kt
> +    private var disposable: Disposable? = null
приватные выше публичных

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newsdetail/NewsDetailViewModel.kt
> +import android.view.View
айайайай плохо. Никакх зависимость от сдк в делегате

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newsdetail/NewsDetailViewModel.kt
> +    override fun onCleared() {
там вроде еще и супер был, можете удалить его, если он пустой, иначе верните на место

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListFragment.kt
> +    @Inject
пустая строка перед инжектом, как вариант можете написать: 
@Inject lateinit var viewModelFactory: ViewModelFactory<NewsListViewModel>

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListFragment.kt
> +            (rv_list_news.adapter as NewsListAdapter).submitList(it)
а зачем кастить, там все равно же будет сабмит лист

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListFragment.kt
> +            if (rv_list_news.adapter == null) {
вынести иницилизацию адаптера из подписки, разная логика

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListFragment.kt
> +            if (it) {
писал выше

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListFragment.kt
> +            this,
писал выше

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListFragment.kt
> +    private fun makeToast(text: String) {
=

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListViewModel.kt
> +                    topNewsInteractor.deleteTopNews().subscribe {
Это логика слоя данных, зачем ее выносить в делегат. можно было мапом все это сделать в интеракторе. Это не должно здесь находится

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListViewModel.kt
> +    override fun onCleared() {
писал выше

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/utils/ViewModelFactory.kt
> +    override fun <T : ViewModel?> create(modelClass: Class<T>): T = viewModel.get() as T
все ж стоит обработать нулл, тут и гет может нулл вернуться и каст тоже может не сработать

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_news_details.xml
> +<layout xmlns:android="http://schemas.android.com/apk/res/android"
две лишние обертки

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_news_details.xml
> +            <ImageView
пустая строка

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/fragment_news_list.xml
> +             android:layout_width="match_parent" android:layout_height="match_parent"
перенос строки

2019-03-27 23:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/news_list_item.xml
> +<LinearLayout
лишняя обертка

2019-03-29 11:11 UTC, KornilovMikhail commented on app/src/main/java/com/github/kornilovmikhail/mvvmandroidproject/ui/fragment/newslist/NewsListFragment.kt
> +            (rv_list_news.adapter as NewsListAdapter).submitList(it)
![image](https://user-images.githubusercontent.com/31703085/55228913-82eb2d00-522c-11e9-9a1c-e20066ab3556.png)

2019-03-30 22:49 UTC, NailShaykhrazievItis approved these changes

2019-03-31 08:03 UTC, merged